package com.workvizo.ui.theme.rooms

import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.*
import androidx.navigation.NavController
import com.workvizo.R
import android.net.Uri


@Composable
fun AiSchedulePreviewScreen(
    navController: NavController,
    userId: String,
    userName: String,
    roomCode: String,
    roomPassword: String
) {
    val decodedUserName = Uri.decode(userName)


    val poppins = FontFamily(Font(R.font.poppins_bold))

    val bgGradient = Brush.verticalGradient(
        listOf(
            Color(0xFF0F2027),
            Color(0xFF203A43),
            Color(0xFF2C5364),
            Color(0xFF6A11CB)
        )
    )

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(bgGradient)
            .verticalScroll(rememberScrollState())
            .padding(20.dp)
    ) {

        /* ---------- HEADER ---------- */
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {

            IconButton(onClick = { navController.popBackStack() }) {
                Icon(Icons.Default.ArrowBack, null, tint = Color.White)
            }

            Image(
                painter = painterResource(id = R.drawable.logo),
                contentDescription = null,
                modifier = Modifier.size(44.dp)
            )
        }

        Spacer(Modifier.height(20.dp))

        Text(
            "AI Generated Schedule",
            fontFamily = poppins,
            fontSize = 24.sp,
            color = Color.White
        )

        Spacer(Modifier.height(8.dp))

        Text(
            "Review the tasks generated by AI. You can edit them before final room creation.",
            fontFamily = poppins,
            fontSize = 14.sp,
            color = Color.White.copy(0.85f)
        )

        Spacer(Modifier.height(30.dp))

        /* ---------- TASKS ---------- */
        AnimatedTaskCard(
            taskNo = "Task 01",
            taskName = "Requirement Analysis",
            start = "2025-02-10",
            end = "2025-02-12",
            poppins = poppins
        )

        Spacer(Modifier.height(18.dp))

        AnimatedTaskCard(
            taskNo = "Task 02",
            taskName = "UI / UX Design",
            start = "2025-02-13",
            end = "2025-02-16",
            poppins = poppins
        )

        Spacer(Modifier.height(40.dp))

        /* ---------- CREATE ROOM BUTTON ---------- */
        Button(
            onClick = {

                val safeUserName = Uri.encode(decodedUserName)

                navController.navigate(
                    "room_created_success/$userId/$safeUserName/$roomCode/$roomPassword"
                )
            }
            ,
            modifier = Modifier
                .fillMaxWidth()
                .height(58.dp),
            shape = RoundedCornerShape(22.dp),
            colors = ButtonDefaults.buttonColors(
                containerColor = Color(0xFF00E5FF)
            )
        ) {
            Text(
                "Create Room",
                fontFamily = poppins,
                fontSize = 18.sp,
                color = Color.Black
            )
        }

        Spacer(Modifier.height(30.dp))
    }
}

/* ---------- TASK CARD ---------- */

@Composable
fun AnimatedTaskCard(
    taskNo: String,
    taskName: String,
    start: String,
    end: String,
    poppins: FontFamily
) {

    val slideAnim = remember { Animatable(80f) }

    LaunchedEffect(Unit) {
        slideAnim.animateTo(0f, tween(700))
    }

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .offset(y = slideAnim.value.dp)
            .clip(RoundedCornerShape(24.dp))
            .background(
                Brush.horizontalGradient(
                    listOf(
                        Color(0xFF7209B7),
                        Color(0xFF560BAD),
                        Color(0xFF3A0CA3)
                    )
                )
            )
            .padding(18.dp)
    ) {

        Column {

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {

                Text(
                    taskNo,
                    fontFamily = poppins,
                    fontSize = 14.sp,
                    color = Color.White
                )

                IconButton(onClick = { /* future edit */ }) {
                    Icon(
                        Icons.Default.Edit,
                        contentDescription = null,
                        tint = Color.White
                    )
                }
            }

            Spacer(Modifier.height(10.dp))

            Text(
                taskName,
                fontFamily = poppins,
                fontSize = 18.sp,
                color = Color.White
            )

            Spacer(Modifier.height(10.dp))

            Row {
                Text(
                    "Start: $start",
                    fontFamily = poppins,
                    fontSize = 12.sp,
                    color = Color.White.copy(0.85f)
                )
                Spacer(Modifier.width(20.dp))
                Text(
                    "End: $end",
                    fontFamily = poppins,
                    fontSize = 12.sp,
                    color = Color.White.copy(0.85f)
                )
            }
        }
    }
}
